Makefile

This PR removes superfluous API Enums

fix: enumerations

---

src/types/page.urls.ts
views/confirm-company.html
views/includes/signout-bar.html
views/layout.html
views/start.html

altering the route from officer-filing to officer-filing-web as officer-filing is used for the healthcheck URL.

DACT-358 changing route as it clashes with the API healthcheck.

---

.gitmodules
README.md
src/app.ts
test/controllers/start.controller.unit.ts
test/global.setup.ts
test/mocks/all.middleware.mock.ts
test/mocks/authentication.middleware.mock.ts
test/mocks/session.middleware.mock.ts
views/start.html

Implement TM01 Start Page with Unit Tests and Matomo Integration
**As an** Officer
**I want to** be presented with an initial guidance screen that is clear and easy to understand
**So that** I can check I am eligible and prepared to start a director removal transaction
[DACT-399](https://companieshouse.atlassian.net/browse/DACT-399)
[DACT-399]: https://companieshouse.atlassian.net/browse/DACT-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DACT-399 Implement TM01 Start Page

---

views/start.html

Move the 'Start now' button slightly further away from the rest of the text
[DACT-399](https://companieshouse.atlassian.net/browse/DACT-399)
[DACT-399]: https://companieshouse.atlassian.net/browse/DACT-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DACT-399 Slightly Move Start Button

---

.gitignore
src/controllers/signout.controller.ts
src/routes/routes.ts
test/controllers/signout.controller.unit.ts
views/signout.html

**As** Companies House
**I want** users to be able to sign out of our services
**So that** it reduces the possibility of another person accessing that account in session and removing a director without the account holder’s permission
[DACT-411](https://companieshouse.atlassian.net/browse/DACT-411)
[DACT-411]: https://companieshouse.atlassian.net/browse/DACT-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DACT-411 Create sign out page

---

Makefile

adding a missed line into the makefile, about api-enumerations.

DACT-414 fixing enumerations.

---

src/controllers/confirm.company.controller.ts

https://companieshouse.atlassian.net/browse/DACT-443
Remove some redundant logging, fix back link

Remove some redundant logging, fix back link

---

views/includes/inputs/date/removal-date-input.html

https://companieshouse.atlassian.net/browse/DACT-386?focusedCommentId=212928
Example removal date updated to match AC

Update example removal date

---

views/remove-director.html

Added Matomo data event id to button on date of remove page:
https://companieshouse.atlassian.net/browse/DACT-425

DACT-425: Add Matomo events for date of remove page

---

views/layout.html

[DACT-458](https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?modal=detail&selectedIssue=DACT-458): Changing feedback link on beta banner
[DACT-458]: https://companieshouse.atlassian.net/browse/DACT-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DACT-485: Updated beta banner feedback link

---

views/remove-director-check-answers.html

Remove automated closing tag insertion

Dact-387 remove automated closing tag insertion

---

views/remove-director-check-answers.html

Fix typo on check your answers page

---

package-lock.json
package.json
src/controllers/remove.director.controller.ts

Get officer name from company appointments rather than expecting it in the filing response from a POST

Dact 532 invalid appointment id bug

---

test/global.setup.ts
views/active-directors.html
views/confirm-company.html
views/remove-director-check-answers.html
views/remove-director-submitted.html
views/remove-director.html
views/service-offline-mid-journey.html
views/stop-page.html

changes so titles and browser tab wordings are all correct

DACT-543 changes so that page titles are all correct and page menu tabs are of the format <Page title> - <Service Name> - GOV.UK

---

src/controllers/remove.director.submitted.controller.ts
views/remove-director-submitted.html

This page should be dynamic to whether an individual company director or corporate director is being removed. The content should be changed depending on what type of director is removed. 
The ‘Removal of a Director Submitted' page is the 9th and final page in the happy path journey for the web service. It acts as a page where an Officer will receive confirmation that the application has been submitted for processing.
This story deals with navigation and links.

DACT-495-submitted-navigation-links

---

src/controllers/active.directors.controller.ts
src/utils/properties.ts
views/active-directors.html

https://companieshouse.atlassian.net/browse/DACT-502
Add appoint director button, hidden behind feature flag. Feature is enabled for local and test environments. 
Local dev config: https://github.com/companieshouse/docker-chs-development/pull/781

Add appoint director button, hidden behind feature flag

---

README.md
src/controllers/director.appointed.date.controller.ts
src/controllers/director.nationality.controller.ts

Small fix to the back links in [the last PR](https://github.com/companieshouse/officer-filing-web/pull/90)

DACT-465 Fix back links on skeleton pages

---

src/controllers/director.occupation.controller.ts
src/utils/format.ts
test/controllers/director.occupation.controller.unit.ts
views/director-occupation.html

Fix some accessibility issues in occupation page HTML
Add director name to occupation page

Fix some accesibility issues

---

package-lock.json
package.json
src/controllers/director.date.of.birth.controller.ts
src/controllers/remove.director.controller.ts
src/model/date.model.ts
src/utils/api.enumerations.keys.ts
src/validation/date.validation.ts
src/validation/dob.date.validation.config.ts
src/validation/remove.date.validation.config.ts
test/controllers/director.date.of.birth.controller.unit.ts
test/controllers/director.name.controller.unit.ts
test/mocks/validation.status.response.mock.ts
test/validation/date.validation.unit.ts
views/director-date-of-birth.html
views/includes/inputs/date/dob-date-input.html

https://companieshouse.atlassian.net/browse/DACT-512
Creating director date of birth screen

DACT-512: Director date of birth screen

---

views/includes/inputs/date/dob-date-input.html

Adjust h1 element for dob page to use the same class as other pages

Adjust h1 element for dob page to use the same class as other pages

---

package-lock.json
package.json
src/controllers/director.appointed.date.controller.ts
src/model/date.model.ts
src/utils/api.enumerations.keys.ts
src/validation/appointment.date.validation.config.ts
test/controllers/director.appointed.date.controller.unit.ts
test/controllers/director.date.of.birth.controller.unit.ts
test/mocks/validation.status.response.mock.ts
views/director-appointed-date.html
views/includes/inputs/date/appoint-date-input.html

https://companieshouse.atlassian.net/browse/DACT-637
Creating the "When was the director appointed?" page - web

DACT-637: Director appointment date screen

---

views/director-nationality.html

Small change to hide nationality3 link on initial page load.

Hide nationality3 link on page load

---

package-lock.json
package.json
src/controllers/director.nationality.controller.ts
src/controllers/director.occupation.controller.ts
test/controllers/director.nationality.controller.unit.ts
test/controllers/director.occupation.controller.unit.ts
views/director-nationality.html

Ensure director name is displayed on page when validation errors are found

Ensure director name is displayed on page when validation errors are found

---

views/start.html

Minor HTML changes to match prototype

Adjust content to match prototype

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

Reverts companieshouse/officer-filing-web#161

Revert "Disable ap01 web for testing"

---

src/controllers/director.protected.details.controller.ts
views/director-protected-details.html

https://companieshouse.atlassian.net/browse/DACT-1004
Fix to remove extra space between title and body
Added padding to continue button

DACT-1004-Does-the-director-have-personal-information-protected-fix

---

src/middleware/company.authentication.middleware.ts
test/middleware/company.authentication.middleware.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1052

DACT-1052 Fixing stop screen appearing after authentication

---

src/controllers/appoint.director.submitted.controller.ts
test/controllers/appoint.director.submitted.unit.ts
views/appoint-director-submitted.html
views/includes/confirm-page-summary.html
views/remove-director-submitted.html

https://companieshouse.atlassian.net/browse/DACT-679

DACT-679 AP01 submission confirmation page

---

src/controllers/appoint.director.submitted.controller.ts
src/controllers/director.correspondence.address.controller.ts
test/controllers/appoint.director.submitted.unit.ts
test/controllers/director.correspondence.address.controller.unit.ts
views/appoint-director-submitted.html
views/includes/confirm-page-summary.html
views/remove-director-submitted.html

https://companieshouse.atlassian.net/browse/DACT-801
Skip registered office address link page if the home address link is already in place.

Dact 801 correspondence link skip

---

src/controllers/director.residential.address.controller.ts
test/controllers/director.residential.address.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1027
Reroute residential address back link if we arrived from the linking page

Reroute residential address back link if we arrived from the linking page

---

views/director-correspondence-address-link.html
views/director-residential-address-link.html

https://companieshouse.atlassian.net/browse/DACT-774?focusedCommentId=227578
Update matomo IDs to be clearer based on product feedback

Update matomo IDs to be clearer based on product feedback

---

views/active-directors.html
views/director-appointed-date.html
views/director-correspondence-address.html
views/director-date-of-birth.html
views/director-residential-address.html
views/remove-director.html

Jira: https://companieshouse.atlassian.net/browse/DACT-842

DACT-842- Changed director name size on top of page

---

src/controllers/director.residential.address.controller.ts
test/controllers/director.residential.address.controller.unit.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-1150
Added conditional render to optional address fields

DACT-1150- Render premise/house number for home address page

---

src/utils/api.enumerations.keys.ts
test/controllers/director.correspondence.address.manual.controller.unit.ts

added error keys in api.enumerations.keys.ts to catch the API errors in the front-end.

DACT-1083 

---

src/controllers/remove.director.submitted.controller.ts
test/controllers/remove.director.submitted.controller.unit.ts

[DACT-851](https://companieshouse.atlassian.net/browse/DACT-851) - Updating format of directors name from combined last name, first name string, to first name, last name on TM01 submission confirmation screen.
[DACT-851]: https://companieshouse.atlassian.net/browse/DACT-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DACT-851: Updating format of directors name on TM01 submission screen

---

views/director-date-details.html

https://companieshouse.atlassian.net/browse/DACT-1160
Minor fix on page HTML spacing

Fix spacing on date details page

---

src/validation/occupation.validation.ts
test/validation/occupation.validation.unit.ts

fix the issue where whitespace was missing from the REGEX for occupation.

DACT-1235 

---

src/controllers/remove.director.submitted.controller.ts

Small change to apply additional formatting to the director's name field on the TM01 submission confirmation screen, to make it consistent with other screens

DACT-851: Director name format

---

src/controllers/director.residential.address.search.controller.ts
src/model/validation.model.ts
src/utils/api.enumerations.keys.ts
src/validation/address.validation.config.ts
src/validation/postcode.validation.ts
test/controllers/director.residential.address.search.choose.address.controller.unit.ts
test/controllers/director.residential.address.search.controller.unit.ts
test/validation/postcode.validation.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1236
Update to frontend validation, including regex for postcode

DACT-1236 Update to frontend validation for home lookup

---

src/validation/occupation.validation.ts
test/controllers/director.occupation.controller.unit.ts

quote the regex, to avoid escaping special characters.

DACT-1235-update-regex-format

---

src/controllers/director.name.controller.ts
src/model/validation.model.ts
src/routes/routes.ts
src/validation/name.validation.config.ts
src/validation/name.validation.ts
test/controllers/director.name.controller.unit.ts
test/validation/name.validation.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1228
Remove backend validation on web for director's name page and replace with frontend validation

DACT-1228: Frontend validation for director name page

---

src/controllers/director.residential.address.controller.ts
test/controllers/director.residential.address.controller.unit.ts
views/director-residential-address.html

https://companieshouse.atlassian.net/browse/DACT-1256
Hide roa radio button on residential address screen if roa was used for correspondence address

Hide roa radio button on residential address screen if roa was used for correspondence address

---

src/controllers/director.residential.address.manual.controller.ts
src/validation/manual.address.validation.ts
src/validation/name.validation.ts
src/validation/occupation.validation.ts
src/validation/postcode.validation.ts
src/validation/validation.ts
test/controllers/director.residential.address.manual.controller.unit.ts

* Also refactored the code to use a single source of truth as REGEX(s) for occupation, name and address validations.

Feature/DACT-1245 JS validations for residential address

---

src/controllers/director.residential.address.controller.ts
test/controllers/director.residential.address.controller.unit.ts
views/director-residential-address.html

https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-1255
Small update to names after recent changes

DACT-1255 - Update to names on recent changes

---

src/utils/constants.ts

https://companieshouse.atlassian.net/browse/DACT-1260
correct error message

correct error message for address linking page

---

src/controllers/director.correspondence.address.controller.ts
src/controllers/director.date.details.controller.ts
src/controllers/director.name.controller.ts
src/controllers/director.nationality.controller.ts
src/controllers/director.occupation.controller.ts
src/controllers/signout.controller.ts
views/includes/back-link.html

Jira: https://companieshouse.atlassian.net/browse/DACT-1226

DACT-1226:  Browser back and No js implementation

---

views/director-date-details.html

https://companieshouse.atlassian.net/browse/DACT-1294

Changing date details title size

---

src/controllers/remove.director.submitted.controller.ts
test/controllers/remove.director.submitted.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1246
Update submission page for TM01 to include full director name

Update submission page for TM01 to include full diretor name

---

src/controllers/director.correspondence.address.controller.ts
src/controllers/director.date.details.controller.ts
src/controllers/director.name.controller.ts
src/controllers/director.nationality.controller.ts
src/controllers/director.occupation.controller.ts
src/utils/web.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-1226
fixed Check your answers back link on browser back

DACT-1226: fixed Check your answers back link on browser back

---

src/validation/nationality.validation.config.ts
src/validation/nationality.validation.ts
test/validation/nationality.validation.unit.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-1234

DACT-1234: fixed error message from blank to select for invalid characters

---

src/validation/date.validation.ts

https://companieshouse.atlassian.net/browse/DACT-1319
Updated regex to not accept 00 or strings longer than 2

DACT-1319-Date Validation bug

---

Makefile

act-1309 fix build command in Makefile

---

package-lock.json
package.json
src/controllers/active.directors.controller.ts
src/controllers/remove.director.controller.ts
test/controllers/active.directors.controller.unit.ts
test/controllers/remove.director.controller.unit.ts
test/mocks/company.appointment.mock.ts
views/includes/corporate-directors.html
views/includes/directors.html

https://companieshouse.atlassian.net/browse/DACT-1482

DACT-1482-post-initial-ch01-filing

---

src/controllers/update/update.director.details.controller.ts
src/controllers/update/update.director.name.controller.ts
test/controllers/update/update.director.name.controller.unit.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-1554

DACT-1554: added redirection to update director details page

---

src/controllers/update/update.director.name.controller.ts
src/routes/routes.ts
views/includes/back-link.html

1: fix to remove browserback condition in backlink html
2: added cho1 feature flag to CHO1 routes
3: added companyAuthentication to ch01 routes

DACT-CH01: remove condition on browser back, companyauthentication to ch01

---

terraform/groups/ecs-service/locals.tf

Minor fix to add missed variable

DACT-1482 Missing update variable

---

package-lock.json
package.json

Bump version of private api sdk

dact-1483 version bump private api sdk

---

locales/en/confirmation.json
src/controllers/update/update.director.submitted.controller.ts
test/controllers/update/update.director.submitted.controller.unit.ts

* also updated incorrect feedback wording.

DACT-1458. update the confirmation page to display the Director name from CHIPS.

---

locales/cy/furniture.json
locales/cy/update-director-details.json
locales/en/furniture.json
locales/en/update-director-details.json
src/controllers/active.directors.controller.ts
src/controllers/update/update.director.details.controller.ts
test/controllers/update/update.director.details.controller.unit.ts
views/includes/check-your-answer/address-details.html
views/update/update-director-details.html

https://companieshouse.atlassian.net/browse/DACT-1591
- English / Welsh (not translated) files added
- Update to update and address details pages for localisation

DACT-1591: Update Director Details Page - English Localisation

---

src/controllers/update/update.director.check.answers.controller.ts
test/controllers/update/update.director.check.answers.controller.unit.ts
views/update/update-director-check-answers.html

https://companieshouse.atlassian.net/browse/DACT-928 - CH01 Check your answers screen

DACT-928: Update director check your answers screen

---

src/controllers/shared.controllers/director.occupation.controller.ts
test/controllers/director.occupation.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1035
Remove BE validation call for occupation page, FE validation achieves the requirement

Remove BE validation call for occupation page, FE validation achieves the requirement

---

views/includes/check-your-answer/address-details.html
views/update/update-director-details.html

Updated class along with css to better match look of prototype
https://companieshouse.atlassian.net/browse/DACT-1555

DACT-1555 Update summary list value to action

---

src/controllers/active.directors.controller.ts
src/controllers/shared.controllers/director.occupation.controller.ts
src/controllers/update/update.director.check.answers.controller.ts
test/controllers/active.directors.controller.unit.ts
test/controllers/update/update.director.occupation.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1035
Add occupation link to cya, ensure None value from CA is handled correctly. Ensure checks for data changes are not case sensitive

Add occupation link to cya, ensure None value from CA is handled correctly. Ensure checks for data changes are not case sensitive

---

views/includes/check-your-answer/address-details.html
views/update/update-director-details.html

No Jira, fix styling of update directors page

Dact fix update director details style distortion

---

locales/cy/director-nationality.json
locales/en/director-nationality.json
src/controllers/shared.controllers/director.nationality.controller.ts
test/controllers/director.nationality.controller.unit.ts
test/controllers/update/update.director.nationality.controller.unit.ts
views/includes/page-templates/director-nationality.html

(Already done under CH01).
* Added tests
* added lang to URL for continues journey in the language selected (if)

DACT-1367 AP01 English localisation for nationality.

---

src/controllers/shared.controllers/director.nationality.controller.ts
test/controllers/update/update.director.nationality.controller.unit.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-1034
- Added Updated ac to unhide multiple nationality if present in chips

enable unhiding more than one nationality

---

views/update/update-director-details.html

Added styling for Details updated pending status from 
To

Update Director pending status styling

---

views/includes/check-your-answer/address-details.html
views/update/update-director-check-answers.html
views/update/update-director-details.html

jira: https://companieshouse.atlassian.net/browse/DACT-1754

DACT-1754: add unique identifiers to elements

---

views/includes/confirm-submit-cancel-button-group.html

have an english default for the confirm and submit button

dact-1362 default the i18n for confirm and submit

---

src/controllers/update/update.director.details.controller.ts
test/controllers/update/update.director.details.controller.unit.ts
views/update/update-director-details.html

Also fixed title case
https://companieshouse.atlassian.net/browse/DACT-1852

DACT-1852 Show middle name on ch01 update page

---

views/remove-director-submitted.html

https://companieshouse.atlassian.net/browse/DACT-1884

DACT-1884 TM01 Submission Page Heading Change

---

src/services/company.appointments.service.ts
test/services/company.appointments.service.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1714

DACT-1714 Obfuscate residential address if officer is secure

---

views/includes/corporate-directors.html
views/includes/directors.html

JIRA https://companieshouse.atlassian.net/browse/DACT-1886
Add a span with hidden text with director name to the director remove & update buttons for accessibility.

dact-1886 add hidden names to buttons

---

views/appoint-director-check-answers.html

https://companieshouse.atlassian.net/browse/DACT-1876

DACT-1876 Removing Consent to Act as page heading

---

views/appoint-director-check-answers.html
views/includes/check-your-answer/address-details.html

https://companieshouse.atlassian.net/browse/DACT-1876
- Consent to Act updated to h2
- Address details cyaDisplay updated to html to include h2 heading

DACT-1876 Consent to Act and Address Details headings update

---

src/controllers/director.correspondence.address.controller.ts
src/controllers/director.correspondence.address.search.controller.ts
src/controllers/director.residential.address.controller.ts
src/controllers/shared.controllers/director.correspondence.address.controller.ts
src/controllers/shared.controllers/director.correspondence.address.search.controller.ts
src/controllers/shared.controllers/director.residential.address.controller.ts
src/controllers/update/update.director.correspondence.address.controller.ts
src/controllers/update/update.director.correspondence.address.search.controller.ts
src/controllers/update/update.director.residential.address.controller.ts
src/utils/render.page.params.ts
test/controllers/shared.controllers/director.correspondence.address.controller.unit.ts
test/controllers/shared.controllers/director.correspondence.address.search.unit.ts
test/controllers/shared.controllers/director.residential.address.controller.unit.ts
test/controllers/update/update.director.submitted.controller.unit.ts

Fix to get director name based on journey type for:
- correspondance address radio button page
- correspondance address postcode lookup page
- residential address radio button page

DACT-1691 - get director name based on Journey - residential address

---

src/controllers/shared.controllers/director.correspondence.address.manual.controller.ts
src/controllers/shared.controllers/director.correspondence.address.search.controller.ts
src/controllers/signout.controller.ts
src/services/stop.page.validation.service.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-1717

dact-1717 4 minor code smells

---

src/controllers/director.residential.address.search.controller.ts
src/controllers/shared.controllers/director.residential.address.search.controller.ts
src/controllers/update/update.director.residential.address.search.controller.ts
test/controllers/shared.controllers/director.residential.address.search.controller.unit.ts
views/includes/page-templates/director-residential-address-search.html

JIRA https://companieshouse.atlassian.net/browse/DACT-2049
Different back link for HA search page when ROA complete

dact-2049 different back when roa complete for HA search page

---

locales/cy/stop-page.json
locales/en/stop-page.json
src/controllers/shared.controllers/director.name.controller.ts
src/controllers/stop.screen.controller.ts
src/utils/constants.ts
test/controllers/stop.screen.controller.unit.ts

JIRA: https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-1382
English localisation for etag stop screen
Page with english localisation:

DACT-1382: Added english localisation for etag stop screen

---

src/middleware/check.your.answers.middleware.ts
src/utils/web.ts
test/middleware/check.your.answers.middleware.unit.ts

JIRA: https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-2100
Fixes issue of not returning to CYA through change links

DACT-2100: Bug-not-returning-to-CYA

---

src/controllers/shared.controllers/director.residential.address.controller.ts
test/controllers/shared.controllers/director.residential.address.controller.unit.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-2085
Address changed flag updates  for the HA radio button page.

dact-2085 ha radio button page should update changed address

---

locales/cy/address.json
locales/cy/errors.json
locales/en/address.json
locales/en/errors.json
src/controllers/shared.controllers/director.correspondence.address.choose.address.controller.ts
src/controllers/shared.controllers/director.residential.address.choose.address.controller.ts
test/controllers/shared.controllers/director.correspondence.address.search.choose.address.controller.unit.ts
test/controllers/shared.controllers/director.residential.address.search.choose.address.controller.unit.ts
views/director-correspondence-address-choose-address.html
views/director-residential-address-search-choose-address.html
views/includes/list/address-array.html

English localisation of postcode look up array pages for correspondence address and home address.

DACT-1373 DACT-1374 

---

locales/cy/common.json
locales/cy/director-confirm-residential-address.json
locales/cy/director-name.json
locales/en/common.json
locales/en/director-confirm-residential-address.json
locales/en/director-name.json
src/controllers/shared.controllers/director.confirm.residential.address.controller.ts
src/controllers/shared.controllers/director.correspondence.address.controller.ts
src/controllers/shared.controllers/director.name.controller.ts
src/controllers/shared.controllers/director.occupation.controller.ts
src/utils/web.ts
test/controllers/shared.controllers/director.confirm.residential.address.controller.unit.ts
views/includes/page-templates/director-confirm-residential-address.html
views/includes/page-templates/director-name.html

Jira: https://companieshouse.atlassian.net/browse/DACT-1377
1: Added localisation for confirm director residential address
2: Fixed localisation redirect on occupation -> correspondence-address -> residential address 
3: fixed partial localisation and redirect on director home page

DACT-1377: WLE-AP01-director-confirm-home-address"

---

locales/cy/director-residential-address-search.json
locales/en/director-residential-address-search.json
src/controllers/shared.controllers/director.residential.address.search.controller.ts
test/controllers/shared.controllers/director.residential.address.search.controller.unit.ts
views/includes/page-templates/director-residential-address-search.html

Add WLE for residential search page
https://companieshouse.atlassian.net/browse/DACT-1370

Add WLE for residential search page

---

locales/cy/furniture.json
views/director-link-correspondence-address-enter-manually.html

https://companieshouse.atlassian.net/browse/DACT-1938
Add localisation for continue button on bad roa page

Add localisation for continue button on bad roa page

---

src/controllers/shared.controllers/director.confirm.residential.address.controller.ts
views/includes/page-templates/director-confirm-residential-address.html

Jira: https://companieshouse.atlassian.net/browse/DACT-1377

DACT-1377: fixed edit residential address backlink param with language

---

src/app.ts

https://companieshouse.atlassian.net/browse/DACT-1977

DACT-1977 Add CH01_active as nunjucks var

---

locales/cy/furniture.json
locales/en/furniture.json
src/controllers/active.directors.controller.ts
src/types/index.ts
src/utils/pagination.ts
test/utils/pagination.unit.ts

* The next, previous and number links on current director does not include the lang param.
* Added Welsh translations for Next and Previous.
* Remove director redirect to redirect in same language selected.

DACT-1424 cosmetic fixes around current director page.

---

src/controllers/director.date.details.controller.ts
src/validation/date.validation.ts
test/validation/date.validation.unit.ts

the changes at the top about appointment. are just spelling mistake changes i noticed so altered,  nothing to do with DACT-2168.  it was spelt as appointement, so i changed it to appointment.

DACT-2168 bug fix for checking age difference > 16 between DOB and DOA.

---

src/validation/date.validation.ts
test/validation/date.validation.unit.ts

JIRA https://github.com/companieshouse/officer-filing-web/pull/398
Change all age validations to use a common more usual way of adding years.

dact-2168 common age diff calcs

---

src/controllers/active.directors.controller.ts

* Back button should take to confirm company with the lang selected
* Changing lang after navigation (ie. on page 3) takes user back to page 1.

DACT-1424 Navigation fixes around current director page with lang selected

---

locales/cy/furniture.json

https://companieshouse.atlassian.net/browse/DACT-2169

Update to signout text

---

locales/cy/director-residential-address-search.json
locales/en/director-residential-address-search.json
src/controllers/shared.controllers/director.residential.address.search.controller.ts

https://companieshouse.atlassian.net/browse/DACT-1370
Back link was missed in previous PR

Fix back link translation for residential search

---

locales/cy/furniture.json
locales/en/furniture.json
views/layout.html

JIRA: https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-1427
Provides English and Welsh localisation for the phase banner

DACT-1427: WLE for beta banner

---

views/signout.html

Added divs for 2/3rds width on signout page

DACT-1437: Fix for text width

---

src/controllers/active.directors.controller.ts
test/controllers/active.directors.controller.unit.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-2077
Set up CHO1 with current address same flags from backend

dact-2077 copy in appointment same as flags on ch01 start

---

views/includes/inputs/fields/postcode-premises-input.html

JIRA https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492/backlog?selectedIssue=DACT-1885
Remove the autocomplete attribute.

dact-1885 remove autocomplete on premises

---

src/utils/address.ts
test/utils/address.unit.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-2181
Addresses in CIDev have been found to be incomplete even though typing of api and documentation would indicate otherwise.

dact-2181 compare addresses with expected fields undefined

---

locales/cy/stop-page.json
src/controllers/stop.screen.controller.ts
src/utils/constants.ts
test/controllers/stop.screen.controller.unit.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-1811

DACT-1811-1812: added language to enter correct date link

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

Disable CH01 for test

---

locales/en/director-correspondence-address-manual.json
views/director-correspondence-address-manual.html

https://companieshouse.atlassian.net/browse/DACT-2218

DACT-2218: CA To Confirm Backlink Text fix

---

src/controllers/shared.controllers/director.name.controller.ts
src/controllers/shared.controllers/director.nationality.controller.ts
src/controllers/update/update.director.nationality.controller.ts
test/controllers/update/update.director.nationality.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-2192
Fixed backlink navigation for nationality page to go to correct page.
Added lang parameter to backlink for name and nationality pages to prevent language choice being lost.

DACT-2192: Fixed back link navigation for nationality

---

locales/cy/director-residential-address-search.json
test/controllers/shared.controllers/director.residential.address.search.controller.unit.ts

JIRA: https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-1401
Adds Welsh translation for AP01 HA lookup page

DACT-1401: WLE AP01 home address lookup page

---

locales/cy/director-residential-address-search.json
test/controllers/shared.controllers/director.residential.address.search.controller.unit.ts

Fixes the Welsh title for Ap01 HA lookup page

Fix DACT-1401: Title correction for AP01 home address lookup page

---

locales/cy/stop-page.json
locales/en/stop-page.json
src/controllers/stop.screen.controller.ts
src/utils/constants.ts
test/controllers/stop.screen.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1940
Localise prohibited company type stop screen

Localise prohibited company type stop screen

---

test/utils/web.unit.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-2316
Fix two minor test compile errors (tests still run but errors jump out if you are watching the world go by...)

dact-2316 fix test compile errors

---

locales/cy/update-director-check-answers.json
src/controllers/update/update.director.check.answers.controller.ts
test/controllers/update/update.director.check.answers.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1421
Add welsh translations

Dact 1421 ch01 cya welsh

---

locales/cy/director-correspondence-address-link.json
locales/cy/errors.json
test/controllers/shared.controllers/director.correspondence.address.link.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-1416
Add complete ROA page welsh translations

Add complete ROA page welsh translations

---

locales/cy/confirmation.json
src/controllers/appoint.director.submitted.controller.ts
src/controllers/update/director.date.of.change.controller.ts
src/controllers/update/update.director.submitted.controller.ts
test/controllers/update/director.date.of.change.controller.unit.ts
test/controllers/update/update.director.submitted.controller.unit.ts

Add lang to post of date-of-change, submission confirmation urls, and a title change

Fix: Add lang to urls and a title change

---

locales/cy/signout.json
test/controllers/signout.controller.unit.ts
views/includes/continue-button.html

https://companieshouse.atlassian.net/browse/DACT-1431
Add welsh translations for signout page

Add welsh translations for signout page

---

locales/cy/furniture.json
locales/en/furniture.json
views/director-link-correspondence-address-enter-manually.html
views/includes/page-templates/director-correspondence-address-link.html

https://companieshouse.atlassian.net/browse/DACT-1416
https://companieshouse.atlassian.net/browse/DACT-1939
Some pages use an alternative word for yes. Delyth has confirmed this is expected.

Fix translation for yes

---

locales/cy/page-not-found.json
test/controllers/error.controller.unit.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-1385

DACT-1385: Added welsh translations and test

---

locales/cy/stop-page.json
locales/en/stop-page.json
src/controllers/shared.controllers/director.nationality.controller.ts
src/controllers/stop.screen.controller.ts
src/utils/constants.ts
test/controllers/stop.screen.controller.unit.ts

* Localisation of Dissolved company stop page.
* WLE translations for the same
* fix the issue where going back to CYA for nationality doesn't maintain the language.

DACT-1387 

---

src/controllers/shared.controllers/director.residential.address.controller.ts
test/controllers/shared.controllers/director.residential.address.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-2225
Updated to include fix for the comma in ROA. Also fixed edge case where if post code does not exist then the comma after the country will now be removed.

DACT-2225 Format addresses on address array page

---

locales/en/director-correspondence-address-link.json
locales/en/director-link-correspondence-address-enter-manually.json

JIRA https://companieshouse.atlassian.net/browse/DACT-1669
correct the English no text.

dact-1669 correct the english no text

---

src/controllers/start.controller.ts
test/controllers/start.controller.unit.ts
views/includes/start-appoint-remove.html
views/includes/start-update.html

JIRA https://companieshouse.atlassian.net/browse/DACT-2419
Fix for start page not setting lang on forward to company lookup

dact-2419 fix for start page not forwarding lang

---

views/update/update-director-submitted.html

JIRA https://companieshouse.atlassian.net/browse/DACT-2165
Swap company number and copnay name on ch01 confirmation screen.

dact-2165 swap number name in ch01 confirmation

---

src/controllers/shared.controllers/director.correspondence.address.manual.controller.ts
src/services/validation.status.service.ts
test/services/validation.status.service.unit.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-2397
Log validation errors so that data and env issues can be triaged more easily.

dact-2397 log validation errors

---

locales/cy/errors.json
src/controllers/shared.controllers/director.nationality.controller.ts
src/controllers/shared.controllers/director.occupation.controller.ts
src/controllers/update/update.director.nationality.controller.ts
src/validation/name.validation.ts
src/validation/nationality.validation.ts
test/controllers/director.name.controller.unit.ts
test/controllers/director.nationality.controller.unit.ts
test/controllers/director.occupation.controller.unit.ts
test/controllers/update/update.director.name.controller.unit.ts
test/controllers/update/update.director.nationality.controller.unit.ts
test/controllers/update/update.director.occupation.controller.unit.ts
test/validation/name.validation.unit.ts

Fix for back link navigation issues when errors are shown on name, nationality, and occupation paages

DACT-2192: error back links fix

---

locales/cy/director-confirm-residential-address.json
locales/cy/director-residential-address-manual.json
locales/en/director-confirm-residential-address.json
locales/en/director-residential-address-manual.json

https://companieshouse.atlassian.net/browse/DACT-2288

DACT-2288: Update content on home address pages

---

src/controllers/start.controller.ts
src/middleware/service.availability.middleware.ts
src/utils/properties.ts
terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/variables.tf
test/global.setup.ts
views/start.html

JIRA https://companieshouse.atlassian.net/browse/DACT-2214
Remove legacy feature flag.

dact-2214 remove old feature flag

---

test/controllers/signout.controller.unit.ts
views/signout.html

Jira: https://companieshouse.atlassian.net/browse/DACT-2421

DACT-2421: fixed signout validation error list href

---

src/controllers/shared.controllers/director.correspondence.address.controller.ts
src/controllers/shared.controllers/director.correspondence.address.manual.controller.ts
test/controllers/start.controller.unit.ts
views/director-correspondence-address-manual.html
views/includes/inset-text/correspondence-inset-text.html
views/includes/start-appoint-remove.html
views/includes/start-update.html
views/service-offline-mid-journey.html

Jira: https://companieshouse.atlassian.net/browse/DACT-2420

Dact 2420 display external links welsh when tm01 ap01 ch01 pages are welsh

---

src/utils/address.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-2448
Compare addresses carefully as expected fields may not be present in actual data.

dact-2448 compare addresses carefully

---

src/controllers/stop.screen.controller.ts
test/controllers/stop.screen.controller.unit.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-568

DACT-568: capitalise stop screen company name

---

views/includes/start-appoint-remove.html
views/includes/start-update.html

Jira: https://companieshouse.atlassian.net/browse/DACT-2420

DACT-2420: fixes external links not expecting params for english localisation

---

src/controllers/stop.screen.controller.ts
test/controllers/stop.screen.controller.unit.ts

Jira: https://companieshouse.atlassian.net/browse/DACT-568

DACT-568: stop page company name to upper case

---

src/utils/address.ts
src/utils/web.ts
test/utils/address.unit.ts

* update the doc for getField().

DACT-2464 Fix a bug with false positive case where an empty string is evaluated as an update in the address field(s)

---

views/includes/start-update.html

Jira: https://companieshouse.atlassian.net/browse/DACT-2388

DACT-2388: fixed protected link name

---

src/utils/localise.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-2497
Set the htmlLang var used by gov uk toolkit.

dact-2497 set htmlLang

---

src/controllers/remove.director.submitted.controller.ts
test/controllers/remove.director.submitted.controller.unit.ts

https://companieshouse.atlassian.net/browse/DACT-671
Update to include name formatting on remove director submitted page 
(date of remove and check your answers pages covered in [previous PR](https://github.com/companieshouse/officer-filing-web/pull/519))

DACT-671 TM01 Formatting Corporate Director Name to Uppercase

---

Makefile
sonar-project.properties

Jira: https://companieshouse.atlassian.net/browse/DACT-1987

DACT-1987: added dependency check

---

package-lock.json
package.json
src/services/company.profile.service.ts
test/controllers/shared.controllers/director.residential.address.controller.unit.ts
test/mocks/active.director.details.mock.ts
test/mocks/company.profile.mock.ts
test/mocks/remove.director.check.answers.mock.ts

JIRA https://companieshouse.atlassian.net/browse/DACT-2289
Remove careOf from officer filing addresses

dact-2289 remove careOf from officer filing

---

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars

dact-config enable ch01 in live

---

README.md

JIRA https://companieshouse.atlassian.net/browse/DACT-2485

dact-2485 Update Web README.md

---

Makefile
sonar-project.properties

Jira: https://companieshouse.atlassian.net/browse/DACT-1987
- Undo make file changes for npm audit and sonar properties

DACT-1987: removed make file npm audit and sonar properties report path

---

package-lock.json

Jira: https://companieshouse.atlassian.net/browse/DACT-1987
Fixed vulnerability with npm audit fix which generated package.lock for follow-redirect vulnerability

DACT-1987: audit fix vulnerability

---

package-lock.json
package.json

JIRA https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-1816
Bump api sdk version

dact-1816 bump api sdk version

---

src/controllers/accessibility.statement.controller.ts

Fixing back link for accessibility statement

DACT-1461: accessibility page back link fix

---

.gitignore
README.md

SEC-90 Update README and gitignore

SEC-90 Update README and gitignore

---

package-lock.json
package.json
sonar-project.properties

**Jira ticket**: ASM-277
Migrate to sonarqube.companieshouse as confluence guide 'Sonarqube Configuration and Migration'
Pipeline PR - https://github.com/companieshouse/ci-pipelines/pull/5362

add sonar.token, remove sonar login and password

---

locales/cy/start.json
locales/en/start.json
nodemon.json
package-lock.json
package.json
src/controllers/start.controller.ts
src/routes/routes.ts
src/utils/properties.ts
test/controllers/start.controller.service.withdrawn.unit.ts
views/includes/start-update.html
views/includes/styles.html

**Jira ticket**: IDVA3-3686
- add condition for Service Withdrawn and not display the start button
- also direct back to Start for all routes
related config:
- https://github.com/companieshouse/docker-chs-development/pull/1992
- https://github.com/companieshouse/ecs-service-configs-dev/pull/1739
- Start screen display
- and also, if the user attempts a url within the service such as `/appoint-update-remove-company-officer/confirm-company?companyNumber=00006400&lang=en` it will redirect back to the Start page
Strikethrough (`~~like this~~`) anything not applicable to your changes.

Disable Start button if Service Withdrawn
