routes.yaml

Had to add -web onto the route as officer-filing is now being used for the API healthcheck as it clashed with another teams route.

DACT-358 changing route as it clashes with the API healthcheck.

---

src/app.ts
src/controllers/error.controller.ts
src/types/template.paths.ts
views/page-not-found.html

[DACT-374](https://companieshouse.atlassian.net/browse/DACT-374)
Create Page Not Found screen:
A 404 error will need to show a 'Page Not Found' screen.
A page not found screen should be shown if someone is trying to view a page that does not exist.
[DACT-374]: https://companieshouse.atlassian.net/browse/DACT-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DACT-391: Page not found screen

---

package-lock.json
package.json

we were broken because of a change made to api-sdk-node,  this is now pointing at a newer version that contains the fix (2.0.68)

Apply fix added to api sdk node

---

src/app.ts
src/middleware/service.availability.middleware.ts
src/utils/properties.ts
test/global.setup.ts
test/middleware/service.availability.middleware.unit.ts
test/mocks/all.middleware.mock.ts
test/mocks/service.availability.middleware.mock.ts

As Companies House
I need features flags to be added for filing the removal of a director via web service
So that I can hide features not yet intended for use 
Context
Refers to an engineering team’s ability to turn a feature or functionality on or off at their discretion.  We need to have such a capability in place for the API and Web service, if we realise there is an issue with a service when we release.
Feature Flag Name | Feature | Option | Active/Inactive | Outcome
-- | -- | -- | -- | --
OFFICER_FILING_WEB_ACTIVE | Web | On | Active | Service pages for the removal of a director
OFFICER_FILING_WEB_ACTIVE | Web | Off | In-active | Only the error 500 page
FEATURE_FLAG_ENABLE_TM01 | API | On | Active | Officer Filing API
FEATURE_FLAG_ENABLE_TM01 | API | Off | In-Active | Error 500 …

Added feature flag

---

Makefile

Force SSH key when resolving dependencies during release build

DACT-424 Force SSH for private dependency during release build

---

src/controllers/active.directors.controller.ts
src/controllers/remove.director.check.answers.controller.ts
src/utils/date.ts
src/utils/format.ts
test/controllers/active.directors.controller.unit.ts
test/controllers/remove.director.check.answers.controller.unit.ts
test/mocks/active.director.details.mock.ts
views/includes/corporate-directors.html
views/includes/directors.html
views/includes/remove-director-check-answers-corporate-summary.html
views/includes/remove-director-check-answers-summary.html

Update appointed on label for pre 1992 appointments. Officers who are missing the appointed_on date are presumed to have been appointed prior to 1992.

Dact 525 appointed on label

---

src/controllers/remove.director.check.answers.controller.ts
src/controllers/remove.director.controller.ts
src/services/remove.directors.error.keys.service.ts
src/services/transaction.service.ts
test/controllers/remove.director.check.answers.controller.unit.ts
test/controllers/remove.director.controller.unit.ts
test/mocks/validation.status.response.mock.ts
test/services/active.director.details.service.unit.ts
test/services/remove.director.date.service.unit.ts
test/services/remove.director.error.keys.service.unit.ts
test/services/transaction.service.unit.ts

The ‘Check your answers before submitting a removal of a Director' page is the 8th page in the happy path journey for the web service. It acts as a page where an Officer will review information such as Name, Date of Birth (for individual directors only), Appointed on and Removal Date to check to see if the information is correct before submitting the TM01. Additionally, there are four types of validation stop screens that occur when the user selects confirm and submit button, the company has already been dissolved, the ETAG is out of date (directors details updated), The service has gone down (API Validation - Error 500) and the director has already been removed. We will also be running and testing all of the back-end validation that needs to ran on this page before a closed transaction …

Dact 461 close transaction

---

src/controllers/stop.screen.controller.ts
src/services/remove.directors.error.keys.service.ts
src/utils/constants.ts
test/controllers/stop.screen.controller.unit.ts
test/mocks/validation.status.response.mock.ts
test/services/remove.director.error.keys.service.unit.ts
views/stop-page.html

This is 1 of 4 stop screens that may occur when a user is on the check your answers page. When the user selects confirm and submit, the information is validated and four errors can occur. This specific stop screen ‘Someone has already made updates for this director' will comprise of the following:
Title: 
-   Someone has already made updates for this director
Content:
- Since you started using this service, someone else has submitted an update to this director's details.
- If you still need to submit this update, you'll need to [start the service again](https://remove-a-director.herokuapp.com/start?journey=gov).
- [Contact us](https://www.gov.uk/contact-companies-house) if you have any questions.
[DACT-434](https://companieshouse.atlassian.net/browse/DACT-434)
[DACT-434]: …

DACT-434 Stop screen - etag is invalid

---

package-lock.json
package.json
src/controllers/remove.director.controller.ts
test/services/remove.director.check.answers.service.unit.ts

Use an updated version of the filing response dto that is returned when either a post or patch is done.
[DACT-504](https://companieshouse.atlassian.net/browse/DACT-504)
[DACT-504]: https://companieshouse.atlassian.net/browse/DACT-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[API PR](https://github.com/companieshouse/officer-filing-api/pull/98)

DACT-504 Update filing response model to use id instead of submissionId

---

views/includes/remove-director-check-answers-corporate-summary.html
views/includes/remove-director-check-answers-summary.html

The remove a director service has an accessibility assessment completed on the 10th of July.
It was raised within the report on the Check your answers page when inspecting the code for the change link
that the visually hidden text refers to address. 
However, it should instead say ‘Date the director was removed from the company'  If we are able to include whatever
the input for the date was within the hidden text without increasing this ticket’s complexity which would be nice to have.
https://companieshouse.atlassian.net/browse/DACT-646

Accessibility audit - Hidden text relating to check your answers page

---

views/remove-director-submitted.html

The remove a director service has an accessibility assessment completed on the 10th of July. 
It was noted in the report -  [Remove-A-Company-Director-Accessibility-Audit.docx](https://companieshouse-my.sharepoint.com/:w:/r/personal/jfrancis_companieshouse_gov_uk/Documents/Remove-A-Company-Director-Accessibility-Audit.docx?d=w9b129640babc4e0caae109b72530b97a&csf=1&web=1&e=Xky9Rm) -
that on the submission confirmation page, the wrong type of header formatting has been applied to the submission confirmation page.
Where on the screen it says What happens next - it is currently using H3 formatting.
This heading needs to be changed so it is using H2.
https://companieshouse.atlassian.net/browse/DACT-647

Accessibility audit - Incorrect Heading tag applied on Submission Confirmation

---

src/controllers/remove.director.controller.ts
src/middleware/validation.middleware.ts
test/controllers/remove.director.controller.unit.ts

When the date of removal page is first landed on, the officers name is shown at the top of the page as expected. The error occurs after an error is displayed to the user.
**Given** a date is entered that passes front-end validation but does not pass API validation (eg date is in the future)
**When** the user hits continue
**Then** The page is refreshed with the error displaying at the top of the page
**And** The officers name is still displayed at the top of the page
[DACT-565](https://companieshouse.atlassian.net/browse/DACT-565)
[DACT-565]: https://companieshouse.atlassian.net/browse/DACT-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DACT-565 re-render director name when validation error occurs

---

src/validation/date.validation.ts

Update the validation logic to be able to highlight multiple fields at once
General tidying to improve reusability of the validation elements
Update existing validation error messages
Move JS validation messages into api-enumerations
[DACT-521](https://companieshouse.atlassian.net/browse/DACT-521)
FIX TO CHECK YEAR IS 4 DIGITS LONG
[DACT-521]: https://companieshouse.atlassian.net/browse/DACT-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Dact-521-Check-Year-Is-4-Digits

---

src/controllers/remove.director.controller.ts

Description
Caught when testing - [[DACT-565] Date of Remove - Director name hidden when error summary component triggered - JIRA (atlassian.net)](https://companieshouse.atlassian.net/browse/DACT-565)
Context:
When a user has entered an invalid date on the date of removal page, the error summary appears at the top of the page.
In the event the user then clicks the back link (possible scenario for this would be if they wanted to check the appointed on date of the director or choose a different director). The user is presented with an error screen.
However the user should be redirected to the current directors page.
Replication steps
Navigate to the Date of Remove page
Input an invalid date and press continue to generate error summary on Date of Remove page
Press the back link button
The …

DACT-655-Error-Screen-Back-Link

---

src/utils/web.ts
test/utils/web.unit.ts

If an officer submits blank data it should save to the Mongo DB, thus creating validation errors.
Issue: returning `undefined` results in null object and json parsing does not take place on api code, thus the patchedData is not updated if user goes back to previous page and clears the text boxes.

DACT-812 return empty string from web instead of undefined

---

README.md
views/includes/styles.html

In older versions of Gov-uk Front end,  it grabs the fonts from  {cdnHost}/fonts/{font name}, which is where the fonts are actually stored in AWS.
The newer version of GOV-UK Front end tries to get the fonts from  {cdnHost}/assets/fonts/{font name}, which then just gets a 404.
This override will make it look for the fonts in the older location,  but it's hardcoded, so prone to possible future breaks. If a permanent solution is come up with, as this will eventually affect all Ch services,  then a change will need to be made.
after speaking to Moses, i will also raise a Jira to get the urls into the config, to make it easier to change them.

DACT-868 adding in a styles override to make it get the fonts from the correct place

---

src/controllers/director.protected.details.controller.ts
test/controllers/director.protected.details.unit.ts

Set the back link to the residential address link page if the flag `isMailingAddressSameAsHomeAddress` set to true.

DACT-1029 

---

src/controllers/stop.screen.controller.ts

use req.originalUrl instead of baseUrl to retain the transactionId and submissionId in the URL when the language toggle is clicked on the 2009 stop page

DACT-2224 

---

test/validation/date.validation.unit.ts

The overage unit test does (today - 110 ) but that is one day out on a leap day. When converted from strings that 1st March so go back 1.

dact-2168 fix for - 110 for leap day

---

views/update/update-director-details.html

JIRA: https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-1556
Adds an event for the "Go back to current directors" button

DACT-1556: Back link flow not registering in Matomo, event missing for go back to current directors
